/**
 * Facade over the translation layer: request bodies, one-shot JSON responses,
 * and SSE line streams. The proxy only talks to this module.
 */
import {
  IrUsage,
  ProtocolId,
  fromIrUsage,
  isObject,
} from "./ir";
import {
  fromAnthropicRequest,
  fromChatCompletionsRequest,
  fromResponsesRequest,
  toAnthropicRequest,
  toChatCompletionsRequest,
  toResponsesRequest,
} from "./request";
import {
  fromAnthropicResponse,
  fromChatCompletionsResponse,
  fromResponsesResponse,
  toAnthropicResponse,
  toChatCompletionsResponse,
  toResponsesResponse,
} from "./response";
import {
  AnthropicParserState,
  Emitter,
  ResponsesParserState,
  createAnthropicEmitter,
  createChatCompletionsEmitter,
  createResponsesEmitter,
  parseAnthropicFrame,
  parseChatCompletionsFrame,
  parseResponsesFrame,
} from "./stream";

export { PROTOCOL_PATHS, protocolForPath, PROTOCOL_IDS } from "./ir";
export type { ProtocolId } from "./ir";

function parseRequest(source: ProtocolId, body: unknown) {
  return source === "openai-completions"
    ? fromChatCompletionsRequest(body)
    : source === "openai-responses"
      ? fromResponsesRequest(body)
      : fromAnthropicRequest(body);
}

function emitRequest(target: ProtocolId, ir: NonNullable<ReturnType<typeof parseRequest>>) {
  return target === "openai-completions"
    ? toChatCompletionsRequest(ir)
    : target === "openai-responses"
      ? toResponsesRequest(ir)
      : toAnthropicRequest(ir);
}

/** Translate a request body between dialects. Null when unparseable. */
export function translateRequestBody(
  source: ProtocolId,
  target: ProtocolId,
  body: unknown,
): Record<string, unknown> | null {
  if (source === target) return null;
  const ir = parseRequest(source, body);
  if (!ir) return null;
  return emitRequest(target, ir);
}

function parseResponse(source: ProtocolId, json: unknown) {
  return source === "openai-completions"
    ? fromChatCompletionsResponse(json)
    : source === "openai-responses"
      ? fromResponsesResponse(json)
      : fromAnthropicResponse(json);
}

/**
 * Translate a complete (non-streaming) upstream response body into the
 * client dialect. Returns null when the body isn't valid JSON, leaving the
 * caller to pass the original bytes through.
 */
export function translateResponseBody(
  source: ProtocolId,
  target: ProtocolId,
  text: string,
  clientModel: string,
): string | null {
  if (source === target) return null;
  let json: unknown;
  try {
    json = JSON.parse(text);
  } catch {
    return null;
  }
  // Error envelopes pass through with their shape adapted just enough for
  // the client's SDK to read the message.
  if (isObject(json) && isObject(json.error)) {
    const message = typeof json.error.message === "string" ? json.error.message : "Upstream error";
    const errorType = typeof json.error.type === "string" ? json.error.type : "upstream_error";
    const shaped =
      target === "anthropic-messages"
        ? { type: "error", error: { type: "api_error", message } }
        : { error: { message, type: errorType } };
    return JSON.stringify(shaped);
  }
  const ir = parseResponse(source, json);
  if (!ir) return null;
  const out =
    target === "openai-completions"
      ? toChatCompletionsResponse(ir, clientModel)
      : target === "openai-responses"
        ? toResponsesResponse(ir, clientModel)
        : toAnthropicResponse(ir, clientModel);
  return JSON.stringify(out);
}

export type UsageAdjuster = (usage: IrUsage) => IrUsage;

function createParser(source: ProtocolId): (frame: Record<string, unknown>) => ReturnType<typeof parseChatCompletionsFrame> {
  if (source === "openai-completions") return parseChatCompletionsFrame;
  if (source === "openai-responses") {
    const state: ResponsesParserState = { toolIndexByOutput: new Map(), toolCount: 0 };
    return (frame) => parseResponsesFrame(frame, state);
  }
  const state: AnthropicParserState = { usage: {}, sawFinish: false };
  return (frame) => parseAnthropicFrame(frame, state);
}

function createEmitter(target: ProtocolId, model: string): Emitter {
  return target === "openai-completions"
    ? createChatCompletionsEmitter(model)
    : target === "openai-responses"
      ? createResponsesEmitter(model)
      : createAnthropicEmitter(model);
}

export type SseTranslator = {
  /** One complete SSE data line (without the "data:" prefix handling) → target lines. */
  translateData(payload: string): string[];
  /** Source stream ended: emit any deferred trailing frames. */
  end(): string[];
};

/**
 * Streaming translator over single SSE data payloads. Frames that carry no
 * translatable content (pings, unknown events) are dropped — the target
 * ceremony is fully regenerated by the emitter.
 */
export function createSseTranslator(
  source: ProtocolId,
  target: ProtocolId,
  clientModel: string,
  adjustUsage?: UsageAdjuster,
): SseTranslator {
  const parse = createParser(source);
  const emitter = createEmitter(target, clientModel);
  return {
    translateData(payload) {
      if (!payload || payload === "[DONE]") return [];
      let frame: Record<string, unknown>;
      try {
        const parsed: unknown = JSON.parse(payload);
        if (!isObject(parsed)) return [];
        frame = parsed;
      } catch {
        return [];
      }
      const events = parse(frame);
      const lines: string[] = [];
      for (const event of events) {
        if (event.type === "usage" && adjustUsage) {
          lines.push(...emitter.push({ type: "usage", usage: adjustUsage(event.usage) }));
        } else {
          lines.push(...emitter.push(event));
        }
      }
      return lines;
    },
    end() {
      return emitter.end();
    },
  };
}
