import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { MessageSquareText } from "lucide-react";
import { toast } from "sonner";
import { api, type FeedbackAttachment, type FeedbackThread } from "@/lib/api";
import { EmptyState, PageHeader } from "@/components/shared";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";

export function FeedbackPage() {
  const qc = useQueryClient(); const query = useQuery({ queryKey: ["admin", "feedback"], queryFn: api.commercial.feedback.list }); const [selected, setSelected] = useState<FeedbackThread | null>(null);
  const refresh = async () => { await qc.invalidateQueries({ queryKey: ["admin", "feedback"] }); const result = await query.refetch(); if (selected) setSelected(result.data?.items.find(item => item.id === selected.id) || null); };
  return <div className="flex flex-col gap-6"><PageHeader title="用户反馈" description="查看反馈状态；打开详情后回复用户或更新处理状态。" /><Card className="overflow-hidden">{!query.data?.items.length ? <EmptyState>{query.isLoading ? "加载中…" : "暂无用户反馈"}</EmptyState> : query.data.items.map(thread => <button key={thread.id} className="flex min-h-14 w-full items-center gap-3 border-b border-border/40 px-4 py-3 text-left text-xs transition-colors last:border-0 hover:bg-secondary/40" onClick={() => setSelected(thread)}><MessageSquareText className="size-4 shrink-0 text-muted-foreground" /><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate font-medium">{thread.subject}</p><span className="truncate text-[11px] text-muted-foreground">{thread.display_name} @{thread.username}</span></div><p className="mt-1 truncate text-[11px] text-muted-foreground">{thread.messages.at(-1)?.body || "图片附件"} · {new Date(thread.updated_at).toLocaleString()}</p></div><Badge variant={thread.status === "open" ? "success" : "secondary"}>{thread.status === "open" ? "处理中" : "已解决"}</Badge></button>)}</Card>{selected ? <FeedbackDialog thread={selected} onClose={() => setSelected(null)} refresh={refresh} /> : null}</div>;
}

function FeedbackDialog({ thread, onClose, refresh }: { thread: FeedbackThread; onClose: () => void; refresh: () => void }) {
  const [body, setBody] = useState(""); const [files, setFiles] = useState<FeedbackAttachment[]>([]); const open = thread.status === "open";
  const reply = useMutation({ mutationFn: () => api.commercial.feedback.reply(thread.id, body, files), onSuccess: () => { setBody(""); setFiles([]); refresh(); }, onError: (e: Error) => toast.error(e.message) });
  const status = useMutation({ mutationFn: () => api.commercial.feedback.status(thread.id, open ? "resolved" : "open"), onSuccess: refresh, onError: (e: Error) => toast.error(e.message) });
  return <Dialog open onOpenChange={value => { if (!value) onClose(); }}><DialogContent className="max-w-[720px]"><DialogHeader><div className="flex items-center justify-between gap-3 pr-6"><DialogTitle>{thread.subject}</DialogTitle><Badge variant={open ? "success" : "secondary"}>{open ? "处理中" : "已解决"}</Badge></div><DialogDescription>{thread.display_name} @{thread.username} · {new Date(thread.created_at).toLocaleString()}</DialogDescription></DialogHeader><div className="mt-4 max-h-[48vh] space-y-2 overflow-y-auto pr-1">{thread.messages.map(message => <div key={message.id} className={`max-w-[88%] rounded-md px-3 py-2 text-xs ${message.sender_type === "admin" ? "ml-auto bg-foreground text-background" : "bg-secondary/55"}`}><p className="whitespace-pre-wrap">{message.body}</p>{message.attachments?.length ? <div className="mt-2 flex flex-wrap gap-2">{message.attachments.map((item, index) => <a key={index} href={item.data} target="_blank" rel="noreferrer"><img src={item.data} alt={item.name} className="h-20 max-w-32 rounded-md object-cover" /></a>)}</div> : null}</div>)}</div>{open ? <div className="space-y-3 border-t border-border/50 pt-4"><Textarea placeholder="回复用户" value={body} onChange={e => setBody(e.target.value)} /><ImageInput files={files} onChange={setFiles} /><DialogFooter><Button variant="secondary" onClick={() => status.mutate()}>标记已解决</Button><Button disabled={(!body.trim() && !files.length) || reply.isPending} onClick={() => reply.mutate()}>发送回复</Button></DialogFooter></div> : <div className="flex items-center justify-between gap-3 rounded-md bg-secondary/45 px-3 py-2"><p className="text-xs text-muted-foreground">用户当前无法继续回复。</p><Button size="sm" variant="secondary" onClick={() => status.mutate()}>重新打开</Button></div>}</DialogContent></Dialog>;
}
function ImageInput({ files, onChange }: { files: FeedbackAttachment[]; onChange: (value: FeedbackAttachment[]) => void }) { return <label className="inline-flex h-8 w-fit cursor-pointer items-center rounded-full bg-secondary px-3 text-xs text-muted-foreground">添加图片{files.length ? ` · ${files.length}` : ""}<input className="hidden" type="file" accept="image/*" multiple onChange={async e => onChange(await Promise.all(Array.from(e.target.files || []).slice(0, 3).map(file => new Promise<FeedbackAttachment>((resolve, reject) => { if (file.size > 2_000_000) return reject(new Error("Image too large")); const reader = new FileReader(); reader.onload = () => resolve({ name: file.name, type: file.type, data: String(reader.result) }); reader.onerror = reject; reader.readAsDataURL(file); }))))} /></label>; }
